[package]
name = "mydhcp"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
etherparse = "0.18.0"
libc = "0.2.172"
log = "0.4.27"
mac_address = "1.1.8"
pcap = "2.2.0"
thiserror = "2.0.12"
